# Generated by Django 5.0.1 on 2024-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_home_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
