# Generated by Django 5.0.1 on 2024-01-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_home_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Home",
            new_name="Apartment",
        ),
    ]
