# Generated by Django 5.0.1 on 2024-01-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_apartment_city_apartment_country_apartment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
