# Generated by Django 5.0.1 on 2024-01-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_apartment_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
