# Generated by Django 5.0.1 on 2024-01-27 21:11

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0013_alter_apartment_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="geolocation",
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
