# Generated by Django 5.0.1 on 2024-02-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0015_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
