# Generated by Django 5.0.1 on 2024-02-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0021_comment_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
