# Generated by Django 5.0.2 on 2024-02-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0025_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="latitude",
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="longitude",
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
