# Generated by Django 5.0.2 on 2024-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0026_notificationpreference_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
