# Generated by Django 5.0.2 on 2024-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0027_notificationpreference_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
