# Generated by Django 5.0.2 on 2024-02-27 12:18

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0028_notificationpreference_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="geolocation",
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
