# Generated by Django 5.0.1 on 2024-02-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_latitude_userprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
